### PR TITLE
feat(listings): status icons for listings

### PR DESCRIPTION
**Pull request by Vheissu**

### CODE REVIEW

**Comment by plwalters** [comment]
@bigopon @Vheissu can you both look at each others icon for this and choose which works best?  (Also I am testing gitter integration)

**Comment by bigopon** [comment]
The difference is a circle around X & tick. So if you feel hard to decide, call for a vote. Or just simply go with Dwayne's one, I have no opinions against this change.

**Comment by bigopon** [comment]
I think lets go for Dwayne version, it's smaller and nicer 👍 

One thing we should have is the direct binding of path d to icon. so instead of 2 `path` and show, lets bind with `d.bind="icon"`. On value change, we just need to changed the icon value in view model ? Last time I was trying to use interpolation but it didn't work. Should work with `bind` I guess. Thoughts ? @PWKad @Vheissu

**Comment by plwalters** [comment]
@Vheissu @bigopon that seems reasonable to me.  Can you push a commit on top of this PR to do that so we can close it out?

**Comment by plwalters** [comment]
Actually I'm going to go ahead and merge this one to get this out in the push I'm about to do, so we can do that separately.

**Pull request merged**
